MainThread 2017-06-02 17:40:46,654 image_match/ERROR/image_match.py:67:test_image_match_001:5725/5648832:{
    "msg": "Traceback (most recent call last):\n  File \"image_match.py\", line 65, in test_image_match_001\n    self.assertEqual(results['total'], 888)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py\", line 515, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py\", line 508, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: 906 != 888\n"
}
MainThread 2017-06-02 17:45:18,320 image_match/ERROR/image_match.py:67:test_image_match_001:5859/5374400:{
    "msg": "Traceback (most recent call last):\n  File \"image_match.py\", line 65, in test_image_match_001\n    self.assertEqual(results['total'], 888)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py\", line 515, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py\", line 508, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: 908 != 888\n"
}
MainThread 2017-06-02 17:45:46,636 image_match/ERROR/image_match_bak.py:67:test_image_match_001:5877/5079488:{
    "msg": "Traceback (most recent call last):\n  File \"image_match_bak.py\", line 65, in test_image_match_001\n    self.assertEqual(results['total'], 888)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py\", line 515, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py\", line 508, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: 908 != 888\n"
}
MainThread 2017-06-02 17:46:53,544 image_match/ERROR/image_match_bak.py:67:test_image_match_001:5912/5550528:{
    "msg": "Traceback (most recent call last):\n  File \"image_match_bak.py\", line 65, in test_image_match_001\n    self.assertEqual(results['total'], 888)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py\", line 515, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py\", line 508, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: 918 != 888\n"
}
